default:
  image: ruby:3.2
  before_script:
    - bundle install --path vendor/bundle

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

rubocop:
  stage: build
  script:
    - bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
  after_script:
    - wget -O sarif-converter --quiet https://gitlab.com/ignis-build/sarif-converter/-/releases/permalink/latest/downloads/bin/sarif-converter-linux
    - chmod +x sarif-converter
    - ./sarif-converter --type codequality rubocop.sarif gl-code-quality-report.json
  artifacts:
    name: rubocop
    paths: [ rubocop.sarif ]
    reports:
      codequality: gl-code-quality-report.json
    when: always

test:
  stage: build
  script:
    - ./bin/rails test
  artifacts:
    name: test
    paths: [ ./test/reports/*.xml ]
    reports:
      junit: ./test/reports/*.xml
    when: always

docker:
  image: docker
  services: [ docker:dind ]
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --tag "$DOCKER_IMAGE"  .
    - docker push "$DOCKER_IMAGE"
