default:
  image: ruby:3.2
  before_script:
    - bundle install --path vendor/bundle

rubocop:
  stage: build
  script:
    - bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
  after_script:
    - wget -O sarif-converter --quiet https://gitlab.com/ignis-build/sarif-converter/-/releases/permalink/latest/downloads/bin/sarif-converter-linux
    - chmod +x sarif-converter
    - ./sarif-converter --type codequality rubocop.sarif gl-code-quality-report.json
  artifacts:
    name: rubocop
    paths: [ rubocop.sarif ]
    reports:
      codequality: gl-code-quality-report.json
    when: always

test:
  stage: build
  script:
    - ./bin/rails test
  artifacts:
    name: test
    paths: [ ./test/reports/*.xml ]
    reports:
      junit: ./test/reports/*.xml
    when: always
